Alex branch
fabianzott/electricity_price_pred pull request #17
Opened 2023-11-29 16:50 UTC by woshou

Hate GitHub

2023-11-29 16:52 UTC, Nepomuk11 requested changes
Dont delete our .env file

2023-11-29 16:57 UTC, Nepomuk11 approved these changes

2023-11-30 09:30 UTC, Nepomuk11 approved these changes
ok!

2023-11-30 09:46 UTC, closed without merging

2023-11-30 09:46 UTC, woshou commented
fix